/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryapp;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class TampilanLibrary extends javax.swing.JFrame {
    //public String dateChooser;
    DefaultTableModel model;
    /**
     * Creates new form Tampilan
     * @throws java.sql.SQLException
     */
    public TampilanLibrary() throws SQLException {
        initComponents();
        
    String [] judul = {"NIM", "Nama", "Kelamin", "Fakultas", "Tglpinjam", "Judul", "Pengarang", "Tglkembali"};
    model = new DefaultTableModel (judul, 0);
    TabelPerpus.setModel(model);
    tampilkan();
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*private void btnCari1(java.awt.event.ActionEvent evt)
    { int row = tabelMahasiswa.getRowCount();
    for(int s = 0; s < row; s++){ model.removeRow(0);*/

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHps = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtNim = new javax.swing.JTextField();
        TxtNama = new javax.swing.JTextField();
        TxtJudul = new javax.swing.JTextField();
        TxtPengarang = new javax.swing.JTextField();
        CbKelamin = new javax.swing.JComboBox();
        DcTglPinjam = new com.toedter.calendar.JDateChooser();
        CbFakultas = new javax.swing.JComboBox();
        DcTglKembali = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPerpus = new javax.swing.JTable();
        BtnSimpan = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        TxtCari1 = new javax.swing.JTextField();
        TxtCari2 = new javax.swing.JTextField();
        BtnCari1 = new javax.swing.JButton();
        BtnCari2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        btnHps.setText("hps");
        btnHps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Fakultas");

        jLabel5.setText("Tanggal Pinjam");

        jLabel6.setText("Judul");

        jLabel7.setText("Pengarang");

        jLabel8.setText("Tanggal Kembali");

        CbKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));

        CbFakultas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FTI", "FH", "FEB", "FKIP", "FBS" }));

        TabelPerpus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPerpus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPerpusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPerpus);

        BtnSimpan.setText("SIMPAN");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnUbah.setText("UBAH");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnKeluar.setText("KELUAR");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });

        BtnCari1.setText("CARI");
        BtnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCari1ActionPerformed(evt);
            }
        });

        BtnCari2.setText("CARI");
        BtnCari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCari2ActionPerformed(evt);
            }
        });

        jLabel9.setText("APLIKASI PERPUSTAKAAN");

        jLabel10.setText("Cari Berdasarkan Fakultas");

        jLabel11.setText("Cari Berdasarkan Jenis Kelamin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNim, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DcTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtPengarang)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(DcTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 78, Short.MAX_VALUE))
                                        .addComponent(TxtJudul))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtCari2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCari1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnSimpan)
                                    .addGap(44, 44, 44)
                                    .addComponent(BtnUbah)
                                    .addGap(49, 49, 49)
                                    .addComponent(BtnHapus))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCari1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnCari2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(42, 42, 42)
                        .addComponent(BtnKeluar)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtNim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CbKelamin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CbFakultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DcTglPinjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtPengarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DcTglKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnUbah)
                    .addComponent(BtnHapus))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCari1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCari2)
                    .addComponent(BtnKeluar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsActionPerformed
       /*  int nim = Integer.parseInt(txtNim.getText());
        
        try {
            Connection conn = getConnection();
            conn.createStatement().executeUpdate("DELETE FROM LIBRARY WHERE NIM='"+nim+"'");
        } catch (SQLException e) {
            System.out.println("Ada error di updatelibrary dengan pesan: " + e.getMessage());
        }
        library();
        resetForm(); */
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHpsActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        long strdate = DcTglPinjam.getDate().getTime();
        long strdata = DcTglKembali.getDate().getTime();
        java.sql.Date pinjam = new java.sql.Date(strdate);
        java.sql.Date kembali = new java.sql.Date(strdata);
        try 
        {
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/test", "root", ""); 
            koneksi.createStatement().executeUpdate("insert into library values" + "('"+TxtNim.getText()+"','"+TxtNama.getText()+"','"+CbKelamin.getSelectedItem()+"','"+CbFakultas.getSelectedItem()+"','"+pinjam+"','"+TxtJudul.getText()+"','"+TxtPengarang.getText()+"','"+kembali+"')");
            tampilkan();
            reset();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        try 
        {
            Connection koneksi  = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "");
            koneksi.createStatement().executeUpdate("delete from library where NIM ='"+TxtNim.getText()+"'");
            tampilkan();
            reset();
        } catch (SQLException ex) 
        {
            Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        try 
        {
        long strdate = DcTglPinjam.getDate().getTime();
        long strdata = DcTglKembali.getDate().getTime();
        java.sql.Date pinjam = new java.sql.Date(strdate);
        java.sql.Date kembali = new java.sql.Date(strdata);
            Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "");
            koneksi.createStatement().executeUpdate("update library set Nama = '"+TxtNama.getText()+"', Kelamin = '"+CbKelamin.getSelectedItem()+"', Fakultas = '"+CbFakultas.getSelectedItem()+"', Tglpinjam = '"+pinjam+"', Judul = '"+TxtJudul.getText()+"', Pengarang = '"+TxtPengarang.getText()+"', Tglkembali = '"+kembali+"' where NIM = '"+TxtNim.getText()+"'");
            tampilkan();
            reset();
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnUbahActionPerformed

    private void TabelPerpusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPerpusMouseClicked
        int i = TabelPerpus.getSelectedRow();
        if(i>-1)
        {    
            TxtNim.setText(model.getValueAt(i, 0).toString());
            TxtNama.setText(model.getValueAt(i, 1).toString());
            CbKelamin.setSelectedItem(model.getValueAt(i, 2).toString());
            CbFakultas.setSelectedItem(model.getValueAt(i, 3).toString());
            DcTglPinjam.setDate((Date) model.getValueAt(i, 4));
            TxtJudul.setText(model.getValueAt(i, 5).toString());
            TxtPengarang.setText(model.getValueAt(i, 6).toString());
            DcTglKembali.setDate((Date) model.getValueAt(i, 7));
        }
            /*int row = TabelPerpus.getSelectedRow();
        
        TxtNim.setText(TabelPerpus.getValueAt(row, 0).toString());
        TxtNama.setText(TabelPerpus.getValueAt(row, 1).toString());
        CbFakultas.setSelectedItem(TabelPerpus.getValueAt(row, 2));
        CbKelamin.setSelectedItem(TabelPerpus.getValueAt(row, 3));
        DcTglKembali.setDate((Date) TabelPerpus.getValueAt(row, 4));
        TxtJudul.setText(TabelPerpus.getValueAt(row, 5).toString());
        TxtPengarang.setText(TabelPerpus.getValueAt(row, 6).toString());
        DcTglPinjam.setDate((Date) TabelPerpus.getValueAt(row, 7)); */
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelPerpusMouseClicked

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
        //System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCari1ActionPerformed
         int row = TabelPerpus.getRowCount();
        for(int s = 0; s < row; s++)
        {
            model.removeRow(0);
        }
        try 
        {
            Connection koneksi;
            koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "");
            ResultSet rs = koneksi.createStatement().executeQuery("select * from library where Fakultas = '"+TxtCari1.getText()+"'");
            while(rs.next()) 
            {      
                  model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getString(3), rs.getString(4),rs.getDate(5), rs.getString(6), rs.getString(7),rs.getDate(8)});     
            }
        } 
            catch(SQLException ex)
            {
                    Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCari1ActionPerformed

    private void BtnCari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCari2ActionPerformed
        int row = TabelPerpus.getRowCount();
        for(int s = 0; s < row; s++)
        {
            model.removeRow(0);
        }
        try 
        {
            Connection koneksi;
            koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "");
            ResultSet rs = koneksi.createStatement().executeQuery("select * from library where Kelamin like '"+TxtCari2.getText()+"' or Fakultas like '"+TxtCari2.getText()+"'");
            while(rs.next()) 
            {     
                  model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getString(3), rs.getString(4),rs.getDate(5), rs.getString(6), rs.getString(7),rs.getDate(8)});                  
            }
            } 
                    catch(SQLException ex)
            {
                  Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);
            }
        /*String key = TxtCari2.getText();
        int row= TabelPerpus.getRowCount();
        for (int i = 0; i < row; i++) {
            tableModel.removeRow(0);
        }
        try {
            String sql = "SELECT * FROM LIBRARY WHERE FAKULTAS='"+key+"' OR KELAMIN='"+key+"'";
            Connection conn = getConnection();
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery(sql);
            if(res.next()){
                tableModel.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getDate(5),res.getString(6),res.getString(7),res.getDate(8)});
            }
            TabelPerpus.setModel(tableModel);
            TxtCari2.setText(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ada error");
        } */      
    // TODO add your handling code here:
    }//GEN-LAST:event_BtnCari2ActionPerformed
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) 
        {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 
            catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> 
        {
            try 
            {
                new TampilanLibrary().setVisible(true);
            }
                catch (SQLException ex) {
                Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCari1;
    private javax.swing.JButton BtnCari2;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox CbFakultas;
    private javax.swing.JComboBox CbKelamin;
    private com.toedter.calendar.JDateChooser DcTglKembali;
    private com.toedter.calendar.JDateChooser DcTglPinjam;
    private javax.swing.JTable TabelPerpus;
    private javax.swing.JTextField TxtCari1;
    private javax.swing.JTextField TxtCari2;
    private javax.swing.JTextField TxtJudul;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtNim;
    private javax.swing.JTextField TxtPengarang;
    private javax.swing.JButton btnHps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void tampilkan()
    {
        int row = TabelPerpus.getRowCount();
        for(int s = 0; s < row; s++)
        {
            model.removeRow(0);
        }
        try 
        {
            Connection koneksi;
            koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "");
            ResultSet rs = koneksi.createStatement().executeQuery("select * from library");
            while(rs.next()) 
        {                  
            model.addRow(new Object[]{rs.getString(1),rs.getString(2), rs.getString(3), rs.getString(4),rs.getDate(5), rs.getString(6), rs.getString(7),rs.getDate(8)});                  
        }
        } 
            catch(SQLException ex)
        {
            Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
    private void reset()
    {
        TxtNim.setText("");
        TxtNama.setText("");
        CbKelamin.setSelectedItem("Laki-laki");
        CbFakultas.setSelectedItem("FTI");
        DcTglPinjam.setDate(null);
        TxtJudul.setText("");
        TxtPengarang.setText("");
        DcTglKembali.setDate(null);
    }
}
    /*
        private void showMahasiswa() {


        int row = tabelMahasiswa.getRowCount();
        for(int s = 0; s < row; s++){
            model.removeRow(0);
        }	
        try {
        Connection koneksi = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/test", "root", "");
        ResultSet rs = koneksi.createStatement().executeQuery("select * from library");
        while(rs.next()){
        String data[] = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
           model.addRow(data);
        }	
        } catch (SQLException ex) {
        Logger.getLogger(TampilanLibrary.class.getName()).log(Level.SEVERE, null, ex);

    }
    */

    


